configuration:  
  projectName: availability-service
#Availability Service Port
server:
 port: 8089

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017
   
logging:
 file: Availability.log
 level: INFO
