configuration:  
  projectName: bungalows-service
#Bungalows Service Port
server:
 port: 8787

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017
   
logging:
 file: Bungalows.log
 level: INFO
