configuration:  
  projectName: region-service
#Region Service Port
server:
 port: 8866
   
logging:
 file: Region.log
 level: INFO

# MongoDB Properties 
spring:
 data:
  mongodb:
   database: MaslDB
   host: localhost
   port: 27017
   maxConnectionsPerHost: 10000
   threadsAllowedToBlockForConnectionMultiplier: 5
   serverSelectionTimeout: 30000
   maxWaitTime: 120000
   connectTimeout: 10000
   socketTimeout: 0
   socketKeepAlive: false
   sslEnabled: false
   sslInvalidHostNameAllowed: false
   alwaysUseMBeans: false 
   heartbeatFrequency: 10000
   minHeartbeatFrequency: 500
   heartbeatConnectTimeout: 20000
   heartbeatSocketTimeout: 20000
   localThreshold: 15
   cursorFinalizerEnabled: true
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
    lease:
      duration: 5
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Term
