configuration:  
  projectName: permits-service
#Permits Service Port
server:
 port: 8095

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017

logging:
 file: Permits.log
 level: INFO
