configuration:  
  projectName: rate-service
#Rate Service Port
server:
 port: 8093

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017
   
logging:
 file: Rate.log
 level: INFO
