configuration:  
  projectName: receipts-service
#Receipts Service Port
server:
 port: 8092

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017
   
logging:
 file: Receipts.log
 level: INFO
 
