configuration:  
  projectName: requestertype-service
#RequesterType Service Port
server:
 port: 8088

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017

logging:
 file: RequesterType.log
 level: INFO
