configuration:  
  projectName: reservation-service
#Reservation Service Port
server:
 port: 8085

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017

logging:
 file: Reservation.log
 level: INFO
