configuration:  
  projectName: tax-service
#Tax Service Port
server:
 port: 8087

#Database properties
spring:
 data:
  mongodb:
   database: ForestDB
   host: localhost
   port: 27017
   
logging:
 file: Tax.log
 level: INFO
